---
- hosts: localhost
  tasks:
  - name: task1
    command: date
    register: result1
    notify: display1
  - name: task2
    command: uptime
    register: result2
    notify: display2
  handlers:
  - name: display1
    debug: var=result1.stdout
  - name: display2
    debug: var=result2.stdout

