---
- hosts: localhost
  tasks:
  - debug: msg="OK1"
  - debug: msg="OK2"
    changed_when: true
  - debug: msg="OK3"
    changed_when: true
    notify: call
  handlers:
  - name: call
    debug: msg="Notified from OK3"
    
