---
- hosts: localhost
  tasks:
  - name: block execution - 1
    block:
    - name: task1
      command: /bin/true 
    - name: task2
      command: /bin/false
    - name: task3
      command: /bin/true 
    ignore_errors: true
    rescue:
    - name: Handle the errors
      debug: msg="recue block"
