---
- hosts: localhost
  tasks:
  - name: block execution - 1
    block:
    - name: task1
      command: /bin/true 
    - name: task2
      command: /bin/false
    - name: task3
      command: /bin/true 
    always:
    - name: Always running block
      debug: msg="Thank you"

  - name: Task-B
    command: echo "Outside the block"
